pipeline {
    agent any 
    tools {nodejs "NodeLatest"}

    stages {
        stage('Dependencies') { 
            steps {
                sh """
                    aws --version
                    node --version
                    yarn --version
                """
            }
        }

        stage("Build") {
            sh "yarn build"
        }

        stage("Deploy") {
            "sh ls"
        }
    }
}