import jenkins.model.*

pipeline {
    agent any 
    tools {nodejs "NodeLatest"}

    environment {
        CLOUDFRONT_ID = "E165NDOJ0Q86CD"
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }

    stages {
        stage('Dependencies') { 
            steps {
                sh """
                    aws --version
                    node --version
                    yarn --version
                """
            }
        }

        stage("Build") {
            steps {
                sh """
                    yarn install
                    yarn build
                """
            }
        }

        stage("Deploy") {
            steps {
                sh '''
                    #!/bin/bash

                    aws s3 sync build/ s3://countdownrockinrio-web

                    CLOUDFRONT_INVALIDATION_ID=\$(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*" | jq ".Invalidation.Id")

                    while :
                    do
                        CLOUDFRONT_INVALIDATION_STATUS=\$(aws cloudfront get-invalidation --id $CLOUDFRONT_INVALIDATION_ID --distribution-id $CLOUDFRONT_ID | jq ".Invalidation.Status")

                        if [ $CLOUDFRONT_INVALIDATION_STATUS = "Completed" ]
                        then
                            echo "CloudFront invalidation status: $CLOUDFRONT_INVALIDATION_STATUS"
                            break
                        fi

                        echo "CloudFront invalidation status: $CLOUDFRONT_INVALIDATION_STATUS"
                        echo "Retry"
                        sleep 5
                    done
                '''
            }
        }
    }
}