pipeline {
    agent any 
    tools {nodejs "NodeLatest"}

    stages {
        stage('Dependencies') { 
            steps {
                sh """
                    aws --version
                    node --version
                    yarn --version
                """
            }
        }

        stage("Deploy") {
            steps {
                sh "yarn build"
            }

            steps {
                "sh ls"
            }
        }
    }
}